#############################################################################################
# 50_fs.conf - part of sysctl configuration file
# Adapted from the following resources:
# - Linux Kernel Self-Protection Project (KSPP): https://kspp.github.io/Recommended_Settings
# - Kicksecure security-misc: https://github.com/Kicksecure/security-misc.git
#
# Documentation:
# - https://www.kernel.org/doc/html/latest/admin-guide/sysctl/
# - https://sysctl-explorer.net/
#############################################################################################
# FS hardening
# https://www.kernel.org/doc/html/latest/admin-guide/sysctl/fs.html

## Definitions:
## KSPP=yes: compliant with recommendations by the KSPP
## KSPP=partial: partially compliant with recommendations by the KSPP
## KSPP=no: not (currently) compliant with recommendations by the KSPP
## If there is no explicit KSPP compliance notice, the setting is not mentioned by the KSPP.

## Prevent hardlink creation by users who do not have read/write/ownership of source file.
## Only allow symlinks to be followed when outside of world-writable sticky directories.
## Allow symlinks when the owner and follower match or when the directory owner matches the symlink's owner.
## Hardens cross-privilege boundaries if root process follows a hardlink/symlink belonging to another user.
## This mitigates many hardlink/symlink-based TOCTOU races in world-writable directories like /tmp.
##
## https://www.kernel.org/doc/html/latest/admin-guide/sysctl/fs.html#protected-symlinks
## https://documentation.ubuntu.com/security/common-mistakes/dangerous-sysctls/
## https://wiki.archlinux.org/title/Security#File_systems
## https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=/tmp
## https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use#Preventing_TOCTOU
##
## KSPP=yes
## KSPP sets the sysctls.
##
fs.protected_hardlinks = 1
fs.protected_symlinks = 1

## Disable POSIX corner cases with creating files and fifos unless the
## directory owner matches.
## Avoid unintentional writes to an attacker-controlled FIFO, where a program
## expected to create a regular file.
##
## https://www.kernel.org/doc/html/latest/admin-guide/sysctl/fs.html#protected-fifos
## https://documentation.ubuntu.com/security/common-mistakes/dangerous-sysctls/
##
## KSPP=yes
## KSPP sets the sysctl.
##
fs.protected_fifos=2
fs.protected_regular=2

## Prevent setuid processes or otherwise protected/tainted binaries from creating core dumps.
## Any process which has changed privilege levels or is execute-only will not be dumped.
##
## https://www.kernel.org/doc/html/latest/admin-guide/sysctl/fs.html#suid-dumpable
## https://blog.qualys.com/vulnerabilities-threat-research/2025/05/29/qualys-tru-discovers-two-local-information-disclosure-vulnerabilities-in-apport-and-systemd-coredump-cve-2025-5054-and-cve-2025-4598
##
## KSPP=yes
## KSPP sets the sysctl.
##
fs.suid_dumpable = 0
