#############################################################################################
# 50_virtual_memory.conf - part of sysctl configuration file
# Adapted from the following resources:
# - Linux Kernel Self-Protection Project (KSPP): https://kspp.github.io/Recommended_Settings
# - Kicksecure security-misc: https://github.com/Kicksecure/security-misc.git
#
# Documentation:
# - https://www.kernel.org/doc/html/latest/admin-guide/sysctl/
# - https://sysctl-explorer.net/
#############################################################################################
# virtual memory (VM) hardening
# https://www.kernel.org/doc/html/latest/admin-guide/sysctl/vm.html

## Definitions:
## KSPP=yes: compliant with recommendations by the KSPP
## KSPP=partial: partially compliant with recommendations by the KSPP
## KSPP=no: not (currently) compliant with recommendations by the KSPP
## If there is no explicit KSPP compliance notice, the setting is not mentioned by the KSPP.

## Maximize bits of entropy for improved effectiveness of mmap ASLR.
## The maximum number of bits depends on CPU architecture (the ones shown below are for x86).
## Both explicit sysctl are made redundant due to automation.
##
## https://forums.whonix.org/t/automate-mmap-randomisation-to-fix-ppc64el/16514
##
vm.mmap_rnd_bits=32
vm.mmap_rnd_compat_bits=16


## Restrict the userfaultfd() syscall to users with SYS_CAP_PTRACE.
## Reduces the likelihood of use-after-free exploits from heap sprays.
##
## https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=cefdca0a86be517bc390fc4541e3674b8e7803b0
## https://duasynt.com/blog/linux-kernel-heap-spray
##
## KSPP=yes
## KSPP sets the sysctl.
##
vm.unprivileged_userfaultfd=0
