#############################################################################################
# 60_misc.conf - part of sysctl configuration file
# Adapted from the following resources:
# - Linux Kernel Self-Protection Project (KSPP): https://kspp.github.io/Recommended_Settings
# - Kicksecure security-misc: https://github.com/Kicksecure/security-misc.git
#
# Documentation:
# - https://www.kernel.org/doc/html/latest/admin-guide/sysctl/
# - https://sysctl-explorer.net/
#############################################################################################
# Misc hardening

## Definitions:
## KSPP=yes: compliant with recommendations by the KSPP
## KSPP=partial: partially compliant with recommendations by the KSPP
## KSPP=no: not (currently) compliant with recommendations by the KSPP
## If there is no explicit KSPP compliance notice, the setting is not mentioned by the KSPP.
## Restrict loading TTY line disciplines to users with CAP_SYS_MODULE.
## Prevents unprivileged users from loading vulnerable line disciplines with the TIOCSETD ioctl.
##
## https://a13xp0p0v.github.io/2017/03/24/CVE-2017-2636.html
## https://lkml.org/lkml/2019/4/15/890
##
## KSPP=yes
## KSPP sets the sysctl does not set CONFIG_LDISC_AUTOLOAD.
##
dev.tty.ldisc_autoload=0
